version: 2.1

references:

# Set working directory
working_directory: &working_directory ~/project

semver_tags: &semver_tags
  tags:
    only: /^v.*/

# Set default configuration
default_config: &default_config
  docker:
    - image: circleci/node:12-stretch
  working_directory: *working_directory

repo_cache_key: &repo_cache_key v1-repo-{{ .Branch }}-{{ .Revision }}

# Step to save repository from cache
save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

jobs:
  before_script:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: npm clean install
          command: npm ci
      - *save_repo

  prettier:
    <<: *default_config
    steps:
      - *restore_repo
      - run:
          name: npm prettier check
          command: |
            npm run prettier:check

  lint:
    <<: *default_config
    steps:
      - *restore_repo
      - run:
          name: npm lint check
          command: |
            npm run lint:check

  test:
    <<: *default_config
    steps:
      - *restore_repo
      - run:
          name: npm test
          command: |
            npm test

  publish:
    <<: *default_config
    steps:
      - *restore_repo
      - run:
          name: authenticate
          command: |
            echo //registry.npmjs.org/:_authToken=${CAZOO_NPM_TOKEN}>.npmrc
      - run:
          name: Publish package
          command: echo "npm publish"

workflows:
  release:
    jobs:
      - before_script:
          name: 'Init'
          filters:
            <<: *semver_tags
      - prettier:
          name: 'Prettier check'
          requires:
            - 'Init'
          filters:
            <<: *semver_tags
      - lint:
          name: 'Lint check'
          requires:
            - 'Init'
          filters:
            <<: *semver_tags
      - test:
          name: 'Run tests'
          requires:
            - 'Init'
          filters:
            <<: *semver_tags
      - publish:
          name: 'Publish package'
          context: cazoo-npm
          requires:
            - 'Run tests'
            - 'Lint check'
            - 'Prettier check'
          filters:
            branches:
              ignore: /.*/
            <<: *semver_tags
