version: 2.1

references:

# Set working directory
working_directory: &working_directory ~/project

# Set default configuration
default_config: &default_config
  docker:
    - image: circleci/node:12-stretch
  working_directory: *working_directory

repo_cache_key: &repo_cache_key v1-repo-{{ .Branch }}-{{ .Revision }}

# Step to save repository from cache
save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

jobs:
  before_script:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: npm clean install
          command: npm ci
      - *save_repo

  prettier:
    <<: *default_config
    steps:
      - *restore_repo
      - run:
          name: npm prettier check
          command: |
            npm run prettier:check

  test:
    <<: *default_config
    steps:
      - *restore_repo
      - run:
          name: npm test
          command: |
            npm test

workflows:
  release:
    jobs:
      - before_script:
          name: 'Init'
      - prettier:
          name: 'Prettier check'
          requires:
            - 'Init'
      - test:
          name: 'Run tests'
          requires:
            - 'Init'
